<?php

namespace AppBundle\Repository;

/**
 * ContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUniqueContributionForSpot($id)
    {
        return $this->createQueryBuilder('c')
            ->select('c')
            ->where('c.spot = :id')
            ->setParameter('id', $id)
            ->groupBy('c.contributor')
            ->orderBy('c.createdAt', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
