<?php

namespace OC\PlatformBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use AppBundle\Entity\Sport;

class LoadSports implements FixtureInterface
{
    public function load(ObjectManager $manager)
    {
        $names = array(
            'Aïkido',
            'Alpinisme',
            'Athlétisme',
            'Aviron',
            'Aérobic',
            'Apnée',
            'Aéromodélisme',
            'Badminton',
            'Balle au tambourin',
            'Bando',
            'Baseball',
            'Base jump',
            'Basket-ball',
            'Bateau-Dragon',
            'Biathlon',
            'Billard',
            'BMX',
            'Bobsleigh',
            'Boot Camp',
            'Bowling',
            'Boxe',
            'Cirque',
            'Canoë-kayak',
            'Canyoning',
            'Course',
            'Course d\'orientation',
            'Cricket',
            'Croquet',
            'Crosse',
            'Crossfit',
            'Curling',
            'Cyclisme',
            'Capoeira',
            'Cheerleading',
            'Conduite sur glace',
            'Catch',
            'Canoë',
            'Curling',
            'Danse',
            'Dames',
            'Deltaplane',
            'Décathlon',
            'Duathlon',
            'Équitation',
            'Escalade',
            'Escrime',
            'Échecs',
            'Équilibriste',
            'Floorball',
            'Football',
            'Football américain',
            'Football australien',
            'Football gaélique',
            'Futsal',
            'Golf',
            'Gymnastique',
            'Gouren',
            'Glisse',
            'Gardien',
            'Hakko-Ryu',
            'Haltérophilie',
            'Handball',
            'Hockey sur gazon',
            'Hockey sur glace',
            'Horse-ball',
            'Hurling',
            'Iaïdo',
            'Iaïjutsu',
            'Jeu de paume',
            'Ju-Jitsu',
            'Joutes nautiques',
            'Judo',
            'Javelot tir sur cible',
            'Jumping',
            'Java',
            'Jerk',
            'Jogging',
            'Kaninhop',
            'Karaté',
            'kathak',
            'Kayak',
            'Kick-boxing',
            'Kitesurfing',
            'Kronum',
            'Karting',
            'Keirin',
            'Kendo',
            'Kempo',
            'Kin-ball',
            'Kung fu',
            'Krav maga',
            'Lancer de disque',
            'Lancer de javelot',
            'Lancer de marteau',
            'Lancer de poids',
            'Luge de course',
            'Lutte',
            'Muay thaï',
            'Motocross',
            'Musculation',
            'Marathon',
            'Marche',
            'Naban',
            'Natation',
            'Natation synchronisée',
            'Nautisme',
            'Netball',
            'Paddle',
            'Padle Tennis',
            'Paintball',
            'Parachutisme',
            'Parapente',
            'Parkour',
            'Patinage artistique',
            'Patinage de vitesse',
            'Pêche',
            'Pelote basque',
            'Pentathlon moderne',
            'Pétanque',
            'Pilates',
            'Ping-Pong',
            'Plongée',
            'Plumfoot',
            'Polo',
            'Qi gong',
            'Quadrille',
            'Quiddich',
            'Rafting',
            'Rallye automobile',
            'Régate',
            'Ringuette',
            'Rink hockey',
            'Roller',
            'Roller in line hockey',
            'Rugby à sept',
            'Rugby à XIII',
            'Rugby à XV',
            'Roller Derby',
            'Savate',
            'Shinty',
            'Skateboard',
            'Skater hockey',
            'Skeleton',
            'Ski alpin',
            'Ski de fond',
            'Ski nordique',
            'Ski nautique',
            'Slamball',
            'Snowboard',
            'Softball',
            'Spéléologie',
            'Squash',
            'Sumo',
            'Surf',
            'Supermotard',
            'Salsa',
            'Saut a ski',
            'Sport boule lyonnaise',
            'Taekwondo',
            'Tambourin',
            'Tae Bo',
            'Tai chi',
            'Taihojutsu',
            'Tchoukball',
            'Tennis',
            'Twirling',
            'Tennis de table',
            'Tir',
            'Tir à l\'arc',
            'Triathlon',
            'Triple saut',
            'Tango',
            'Tricking',
            'ULM',
            'Ultimate',
            'Unihockey',
            'Ultra-trail',
            'Varappe',
            'Voile',
            'Volata',
            'Volley-ball',
            'VTT',
            'Voltige',
            'Valse',
            'Wakeboard',
            'Water polo',
            'Wing Chun',
            'Yoga',
            'Zen Hakko Kaï',
            'Zumba',
            'Zouk'
        );

        foreach ($names as $name) {
            $category = new Sport();
            $category->setName($name);
            $manager->persist($category);
        }

        $manager->flush();
    }
}